# Generated by Django 3.2.5 on 2021-08-24 21:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0011_alter_investoruser_activation_key_expires'),
    ]

    operations = [
        migrations.AlterField(
            model_name='investoruser',
            name='activation_key_expires',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 26, 21, 2, 31, 151104)),
        ),
    ]
