# Generated by Django 3.2.5 on 2021-09-17 11:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0014_alter_investoruser_activation_key_expires'),
    ]

    operations = [
        migrations.AlterField(
            model_name='investoruser',
            name='activation_key_expires',
            field=models.DateTimeField(default=datetime.datetime(2021, 9, 19, 11, 12, 59, 608818)),
        ),
    ]
