# Generated by Django 3.2.5 on 2021-08-25 15:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('mainapp', '0002_productcategory_short_desc'),
    ]

    operations = [
        migrations.CreateModel(
            name='Model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='наименование')),
                ('short_desc', models.CharField(blank=True, max_length=256, verbose_name='краткое описание')),
                ('description', models.TextField(blank=True, verbose_name='описание')),
                ('is_active', models.BooleanField(default=True, verbose_name='активна')),
            ],
            options={
                'verbose_name': 'модель предсказаний',
                'verbose_name_plural': 'модели предсказаний',
            },
        ),
        migrations.CreateModel(
            name='Prediction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(verbose_name='дата')),
                ('price', models.DecimalField(decimal_places=5, default=0, max_digits=12, verbose_name='цена')),
                ('signal', models.CharField(choices=[('1', 'покупка'), ('-1', 'продажа'), ('0', 'удержание'), ('9', 'разворот ценового движения')], default='0', max_length=2, verbose_name='сигнал')),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modelapp.model')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.product')),
            ],
            options={
                'verbose_name': 'сигнал модели для фин.продукта',
                'verbose_name_plural': 'сигналы для фин.продукта(ов)',
            },
        ),
    ]
