# Generated by Django 3.2.5 on 2021-09-09 15:37

import datetime
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('modelapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='prediction',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='prediction',
            name='date_expires',
            field=models.DateTimeField(default=datetime.datetime(2021, 9, 9, 21, 36, 21, 880144)),
        ),
    ]
