# Generated by Django 3.2.5 on 2021-08-25 22:05

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('modelapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Signal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='наименование')),
                ('is_active', models.BooleanField(default=True, verbose_name='активный')),
            ],
            options={
                'verbose_name': 'сигнал',
                'verbose_name_plural': 'сигналы',
            },
        ),
        migrations.AlterModelOptions(
            name='prediction',
            options={'verbose_name': 'предсказание модели для фин.продукта', 'verbose_name_plural': 'предсказания для фин.продукта(ов)'},
        ),
        migrations.AddField(
            model_name='prediction',
            name='date_expires',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 26, 4, 5, 16, 488585)),
        ),
        migrations.AddField(
            model_name='prediction',
            name='percent',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='процент (доля)'),
        ),
        migrations.AlterField(
            model_name='prediction',
            name='signal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modelapp.signal'),
        ),
    ]
