# Generated by Django 3.2.5 on 2021-09-16 12:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modelapp', '0006_auto_20210909_1543'),
    ]

    operations = [
        migrations.AddField(
            model_name='prediction',
            name='optional_information',
            field=models.TextField(blank=True, verbose_name='дополнительная информация'),
        ),
        migrations.AddField(
            model_name='signal',
            name='description',
            field=models.CharField(blank=True, max_length=256, verbose_name='краткое описание'),
        ),
        migrations.AlterField(
            model_name='prediction',
            name='date_expires',
            field=models.DateTimeField(default=datetime.datetime(2021, 9, 16, 18, 6, 33, 784752)),
        ),
    ]
