# Generated by Django 3.2.5 on 2021-08-24 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='productcategory',
            name='short_desc',
            field=models.CharField(blank=True, max_length=256, verbose_name='краткое описание'),
        ),
    ]
